### ISSUE TITLE
issue jahoda

### ISSUE THREAD

**Issue by jalesko** [Adriana-dev-ops/DevOps-2021-september#1]
jahodka.md ma mat minimalne 3 titulky

**Comment by Adriana-dev-ops** [comment]
dobre sefe

**Comment by Adriana-dev-ops** [comment]
A82089939@DESKTOP-CR8TI67 MINGW64 ~/DevOps-2021-september/fruits (issue-jahodka)
$ git push --set-upstream origin issue-jahodka
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 793 bytes | 793.00 KiB/s, done.
Total 7 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
remote:
remote: Create a pull request for 'issue-jahodka' on GitHub by visiting:
remote:      https://github.com/Adriana-dev-ops/DevOps-2021-september/pull/new/issue-jahodka
remote:
To https://github.com/Adriana-dev-ops/DevOps-2021-september.git
 * [new branch]      issue-jahodka -> issue-jahodka
Branch 'issue-jahodka' set up to track remote branch 'issue-jahodka' from 'origin'.

**Comment by jalesko** [comment]
ok upravene
